blank_issues_enabled: false
contact_links:
  - name: Make a suggestion
    url: https://github.com/rubyonmac/rubyonmac-issues/discussions
    about: Suggest a feature you'd like to see in a future Ruby on Mac Prime update.
